
services:
  db:
    image: postgres:16-alpine
    container_name: kwanzafolha_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: hr_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5434:5432"   # <- host:container. Fora é 5434, dentro continua 5432
    volumes:
      - kwanzafolha_pg_data:/var/lib/postgresql/data
      - ./db:/db      # monta a pasta db/ dentro do container, em /db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  kwanzafolha_pg_data:
